### ISSUE TITLE
Cyclic dependency involving node 'white' detected while reading an SVG created by codecov.

### ISSUE THREAD

**Issue by bric3** [weisJ/jsvg#91]
Suppose the following SVG created by https://codecov.io tool

![](https://camo.githubusercontent.com/ca6f04cc3d7d26ba9f9bce39862c3b44db4ffb93683580829f33b7940433d6d2/68747470733a2f2f636f6465636f762e696f2f67682f73706f636b6672616d65776f726b2f73706f636b2f70756c6c2f313235302f6772617068732f747265652e7376673f77696474683d363530266865696768743d313530267372633d707226746f6b656e3d786e773657457a64566f)

With JSVG 1.6.1, the following code fails with the cyclic dependency.

```java
new SVGLoader().load(URI.create("https://camo.githubusercontent.com/ca6f04cc3d7d26ba9f9bce39862c3b44db4ffb93683580829f33b7940433d6d2/68747470733a2f2f636f6465636f762e696f2f67682f73706f636b6672616d65776f726b2f73706f636b2f70756c6c2f313235302f6772617068732f747265652e7376673f77696474683d363530266865696768743d313530267372633d707226746f6b656e3d786e773657457a64566f").toURL())
```

```text
Oct 03, 2024 11:03:55 AM com.github.weisj.jsvg.parser.css.impl.SimpleCssParser$Parser expected
WARNING: Expected 'CURLY_OPEN' but got 'Token{type=CLASS_NAME, data='s'}'
Oct 03, 2024 11:03:55 AM com.github.weisj.jsvg.parser.css.impl.SimpleCssParser$Parser expected
WARNING: Expected 'CURLY_OPEN' but got 'Token{type=EOF, data='null'}'
Oct 03, 2024 11:03:55 AM com.github.weisj.jsvg.parser.SVGLoader load
WARNING: Could not load SVG 
java.lang.IllegalStateException: Cyclic dependency involving node 'white' detected.
	at com.github.weisj.jsvg.parser.ParsedElement.cyclicDependencyDetected(ParsedElement.java:126)
	at com.github.weisj.jsvg.parser.ParsedElement.nodeEnsuringBuildStatus(ParsedElement.java:83)
	at com.github.weisj.jsvg.parser.ParsedDocument.getElementById(ParsedDocument.java:53)
	at com.github.weisj.jsvg.parser.DefaultElementLoader.loadElement(DefaultElementLoader.java:56)
	at com.github.weisj.jsvg.parser.AttributeNode.getElementByUrl(AttributeNode.java:126)
	at com.github.weisj.jsvg.parser.AttributeNode.getPaint(AttributeNode.java:186)
	at com.github.weisj.jsvg.renderer.PaintContext.parse(PaintContext.java:78)
	at com.github.weisj.jsvg.nodes.ShapeNode.build(ShapeNode.java:84)
	at com.github.weisj.jsvg.parser.ParsedElement.build(ParsedElement.java:116)
	at com.github.weisj.jsvg.parser.ParsedElement.build(ParsedElement.java:114)
	at com.github.weisj.jsvg.parser.ParsedElement.build(ParsedElement.java:114)
	at com.github.weisj.jsvg.parser.ParsedElement.build(ParsedElement.java:114)
	at com.github.weisj.jsvg.parser.SVGDocumentBuilder.build(SVGDocumentBuilder.java:178)
	at com.github.weisj.jsvg.parser.StaxSVGLoader.load(StaxSVGLoader.java:169)
	at com.github.weisj.jsvg.parser.SVGLoader.load(SVGLoader.java:111)
	at com.github.weisj.jsvg.parser.SVGLoader.load(SVGLoader.java:62)
	at com.github.weisj.jsvg.parser.SVGLoader.load(SVGLoader.java:54)
	at com.github.weisj.jsvg.parser.SVGLoader.load(SVGLoader.java:49)
	at sandbox.swing.QuickImageViewer.main(QuickImageViewer.kt:35)
```

SVG attached : [treemap](https://github.com/user-attachments/assets/da93170a-3126-44a0-833c-1e02783b1632)

**Comment by weisJ** [comment]
From a quick glance I think the following is happening: The CSS parser is incorrectly applying the `rect.s` rule to the `rect` inside the `patter#white` which tries to applies the mask referencing said pattern.

**Comment by bric3** [comment]
I'm not sure on how to help fix that at this time 😵

**Comment by weisJ** [comment]
The current CSS parser is very rudimentary. I am currently working on a bit more advanced version which should support loads more selectors.

**Comment by weisJ** [comment]
See #93

**Comment by bric3** [comment]
Thank you, I'll try to find some time to try code in #94.

**Comment by bric3** [comment]
@weisJ Looks good with #94 
<img width="1103" alt="image" src="https://github.com/user-attachments/assets/d0b94269-c7b7-4264-82be-9238d1a2b782">

On master the view fails with mentioned stack trace:

```
Oct 26, 2024 10:48:18 PM com.github.weisj.jsvg.parser.css.impl.SimpleCssParser$Parser expected
WARNING: Expected 'CURLY_OPEN' but got 'Token{type=CLASS_NAME, data='s'}'
Oct 26, 2024 10:48:18 PM com.github.weisj.jsvg.parser.css.impl.SimpleCssParser$Parser expected
WARNING: Expected 'CURLY_OPEN' but got 'Token{type=EOF, data='null'}'
Oct 26, 2024 10:48:18 PM com.github.weisj.jsvg.parser.SVGLoader load
WARNING: Could not load SVG 
java.lang.IllegalStateException: Cyclic dependency involving node 'white' detected.
	at com.github.weisj.jsvg.parser.ParsedElement.cyclicDependencyDetected(ParsedElement.java:126)
	at com.github.weisj.jsvg.parser.ParsedElement.nodeEnsuringBuildStatus(ParsedElement.java:83)
	at com.github.weisj.jsvg.parser.ParsedDocument.getElementById(ParsedDocument.java:53)
...
```

**Comment by bric3** [comment]
I don't know if that's something that could interest you either for correctness or performance, but I tried the viewer with some d3js examples. Without noticing issues.

![chart](https://github.com/user-attachments/assets/f0465d01-e1cb-42c0-bb71-35a809021b62)
![chord-diagram](https://github.com/user-attachments/assets/d6102234-1939-4688-921f-e08438272986)
![hierarchical-edge-bundling-II](https://github.com/user-attachments/assets/acf11d77-9b12-4114-8438-cad9adddc942)
![stacked-bar chart-horizontal](https://github.com/user-attachments/assets/8745afde-46aa-447c-a741-55827a291b03)
![streamgraph-transitions](https://github.com/user-attachments/assets/0da1ba28-0ed2-4981-a0b8-fabec38cf98e)
![sunburst](https://github.com/user-attachments/assets/fd8ad8f0-fdce-4cd3-924a-d927995d21a6)
![treemap](https://github.com/user-attachments/assets/0a2d7a85-f2e8-4502-90e1-a0fe6e558c0f)
![vector-tiles](https://github.com/user-attachments/assets/8010ef73-5128-41de-aaa4-632a52886989)
![watercolor](https://github.com/user-attachments/assets/e5754c87-8cac-4bf4-a8c2-69027053416a)
![voronoi](https://github.com/user-attachments/assets/8bfddcae-4341-4c67-aca6-5037224f0c0d)

**Comment by weisJ** [comment]
Should be fixed with the latest version.
